chore(dbadmin): handle force migration version if database is dirty
RedHatInsights/vuln4shift-backend pull request #161
Opened 2022-12-20 12:14 UTC by michalslomczynski

Discovered during debugging that `dbadmin` does not handle dirty DB state.
Completely optional right now.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2023-01-02 16:30 UTC, jdobes requested changes

2023-01-02 16:30 UTC, jdobes commented on dbadmin/dbadmin.go
> +		err = m.Force(schemaMigration) // Force specified migration version if DB is dirty
Lets add some additional check here, the default value is `-1` and the `Force` function will probably fail with that? For example force the version only when `schemaMigration > 0`, this means it'll not force anything until somebody comes and sets the specific version manually.

2023-01-04 12:07 UTC, yungbender approved these changes

2023-01-05 10:31 UTC, jdobes approved these changes

2023-01-05 10:31 UTC, merged