Add basic /cves/:cveName/exposed_clusters api endpoint
RedHatInsights/vuln4shift-backend pull request #28
Opened 2022-04-27 13:46 UTC by blayson

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2022-05-04 14:43 UTC, jdobes requested changes

2022-05-04 14:43 UTC, jdobes commented on manager/controllers/cves/exposed.go
> +	return c.Conn.Table("cluster").
Query doesn't filter by account, it shouldn't return all clusters in DB.

2022-05-06 12:12 UTC, blayson commented
I have changed `generate_swagger.sh` script to follow https://github.com/koalaman/shellcheck/wiki/SC2181
Added swagger documentation and change `db query` filter by `account ID`

2022-05-09 09:26 UTC, jdobes approved these changes

2022-05-09 09:26 UTC, merged